spring:
  application:
    name: montroe-blog-cms-be

  liquibase:
    enabled: false

  servlet:
    multipart:
      max-file-size: 6MB
      max-request-size: 6MB
cms:
  admin:
    email: ${CMS_ADMIN_EMAIL:}
    password: ${CMS_ADMIN_PASSWORD:}

r2:
  endpoint: ${R2_ENDPOINT:http://localhost}
  access-key: ${R2_ACCESS_KEY_ID:test}
  secret-key: ${R2_SECRET_ACCESS_KEY:test}
  bucket: ${R2_BUCKET_NAME:test}